# Generated by Django 2.0.1 on 2019-02-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_create_initial_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='answer',
            field=models.ManyToManyField(to='classroom.Answer'),
        ),
    ]
